component_management:
  individual_components:
    - component_id: "project"
      paths:
        - "./"

comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment
