component_management:
  individual_components:
    - component_id: "commands"
      name: "Commands"
      paths:
        - "Command/**"

    - component_id: "controllers"
      name: "Controllers"
      paths:
        - "Controller/**"

    - component_id: "data_collectors"
      name: "Data collectors"
      paths:
        - "DataCollector/**"

    - component_id: "data_fixtures"
      name: "Data fixtures"
      paths:
        - "DataFixtures/**"

    - component_id: "dependency_injections"
      name: "Dependency injections"
      paths:
        - "DependencyInjection/**"

    - component_id: "forms"
      name: "Forms"
      paths:
        - "Form/**"

    - component_id: "loggers"
      name: "Loggers"
      paths:
        - "Logger/**"

    - component_id: "requests"
      name: "Requests"
      paths:
        - "Request/**"

    - component_id: "resources"
      name: "Resources"
      paths:
        - "Resource/**"

    - component_id: "security"
      name: "Security"
      paths:
        - "Security/**"

    - component_id: "services"
      name: "Services"
      paths:
        - "Service/**"

    - component_id: "twig"
      name: "Twig"
      paths:
        - "Twig/**"

    - component_id: "utils"
      name: "Utils"
      paths:
        - "Util/**"

    - component_id: "validators"
      name: "Validators"
      paths:
        - "Validator/**"

comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment
