services:
  debian:
    container_name: propel-bundle-debian
    build:
      context: ../..
      dockerfile: misc/docker/Dockerfile-debian
    environment:
      SYMFONY_REQUIRE: "6.4"
      PHP: "8.1"
    volumes:
      - ../..:/app
  ubuntu:
    container_name: propel-bundle-ubuntu
    build:
      context: ../..
      dockerfile: misc/docker/Dockerfile-ubuntu
    environment:
      SYMFONY_REQUIRE: "6.4"
      PHP: "8.1"
    volumes:
      - ../..:/app
  alpine:
    container_name: propel-bundle-alpine
    build:
      context: ../..
      dockerfile: misc/docker/Dockerfile-alpine
    environment:
      SYMFONY_REQUIRE: "6.4"
      PHP: "81"
    volumes:
      - ../..:/app