FROM debian:13

ENV SYMFONY_REQUIRE=8.1
ENV PHP=8.4
ENV COMPOSER_ALLOW_SUPERUSER=1

WORKDIR /app

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y composer git zip php$PHP \
    php$PHP-curl \
    php$PHP-intl \
    php$PHP-mbstring \
    php$PHP-mysql \
    php$PHP-pdo \
    php$PHP-pgsql \
    php$PHP-simplexml \
    php$PHP-sqlite3 \
    php$PHP-tokenizer \
    php$PHP-xml \
    php$PHP-xmlwriter

RUN apt-get autoremove -y && apt-get autoclean -y
RUN update-alternatives --set php /usr/bin/php$PHP

COPY . /app
RUN composer global config --no-plugins allow-plugins.symfony/flex true
RUN composer global require --no-progress --no-scripts --no-plugins symfony/flex
RUN SYMFONY_REQUIRE=$SYMFONY_REQUIRE composer u --prefer-dist -n

CMD ["php", "vendor/bin/phpunit"]
