FROM alpine:3

ENV SYMFONY_REQUIRE=7.4
ENV PHP=82
ENV COMPOSER_ALLOW_SUPERUSER=1

WORKDIR /app

RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime \
    && echo $CONTAINER_TIMEZONE > /etc/timezone
COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

RUN apk update && apk upgrade
# Alpine 3.22 has PHP 8.2
RUN apk add ca-certificates \
    && echo "https://dl-cdn.alpinelinux.org/alpine/v3.22/community" >> /etc/apk/repositories
RUN apk del php
RUN apk add git zip php$PHP \
    php$PHP-curl \
    php$PHP-intl \
    php$PHP-mbstring \
    php$PHP-pdo \
    php$PHP-pdo_mysql \
    php$PHP-pdo_pgsql \
    php$PHP-pdo_sqlite \
    php$PHP-simplexml \
    php$PHP-tokenizer \
    php$PHP-xml \
    php$PHP-xmlwriter

RUN rm /usr/bin/php && ln -s /usr/bin/php81 /usr/bin/php

COPY . /app
RUN composer global config --no-plugins allow-plugins.symfony/flex true
RUN composer global require --no-progress --no-scripts --no-plugins symfony/flex
RUN SYMFONY_REQUIRE=$SYMFONY_REQUIRE composer u --prefer-dist -n

CMD ["php", "vendor/bin/phpunit"]
