FROM alpine:3

ENV SYMFONY_REQUIRE=8.1
ENV PHP=84
ENV COMPOSER_ALLOW_SUPERUSER=1

WORKDIR /app

RUN apk update && apk upgrade
RUN apk add composer git zip php$PHP \
    php$PHP-curl \
    php$PHP-intl \
    php$PHP-mbstring \
    php$PHP-pdo \
    php$PHP-pdo_mysql \
    php$PHP-pdo_pgsql \
    php$PHP-pdo_sqlite \
    php$PHP-simplexml \
    php$PHP-tokenizer \
    php$PHP-xml \
    php$PHP-xmlwriter

RUN rm /usr/bin/php && ln -s /usr/bin/php81 /usr/bin/php

COPY . /app
RUN composer global config --no-plugins allow-plugins.symfony/flex true
RUN composer global require --no-progress --no-scripts --no-plugins symfony/flex
RUN SYMFONY_REQUIRE=$SYMFONY_REQUIRE composer u --prefer-dist -n

CMD ["php", "vendor/bin/phpunit"]
