FROM debian:13

ENV SYMFONY_REQUIRE=7.4
ENV PHP=8.2
ENV COMPOSER_ALLOW_SUPERUSER=1

WORKDIR /app

RUN apt-get update
RUN apt-get install -y apt-transport-https lsb-release ca-certificates wget
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y composer git zip php$PHP \
    php$PHP-curl \
    php$PHP-intl \
    php$PHP-mbstring \
    php$PHP-mysql \
    php$PHP-pdo \
    php$PHP-pgsql \
    php$PHP-simplexml \
    php$PHP-sqlite3 \
    php$PHP-tokenizer \
    php$PHP-xml \
    php$PHP-xmlwriter

RUN apt-get autoremove -y && apt-get autoclean -y
RUN update-alternatives --set php /usr/bin/php$PHP

COPY . /app
RUN composer global config --no-plugins allow-plugins.symfony/flex true
RUN composer global require --no-progress --no-scripts --no-plugins symfony/flex
RUN SYMFONY_REQUIRE=$SYMFONY_REQUIRE composer u --prefer-dist -n

CMD ["php", "vendor/bin/phpunit"]
