FROM ubuntu:24.04

ENV SYMFONY_REQUIRE=5.4
ENV PHP=7.4
ENV COMPOSER_ALLOW_SUPERUSER=1

WORKDIR /app

# Forces to use an old version of Composer for PHP 8.0
COPY --from=composer:2.2 /usr/bin/composer /usr/local/bin/composer

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:ondrej/php
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y git zip php$PHP \
    php$PHP-curl \
    php$PHP-intl \
    php$PHP-mbstring \
    php$PHP-mysql \
    php$PHP-pdo \
    php$PHP-pgsql \
    php$PHP-simplexml \
    php$PHP-sqlite3 \
    php$PHP-tokenizer \
    php$PHP-xml \
    php$PHP-xmlwriter

RUN apt-get autoremove -y && apt-get autoclean -y
RUN update-alternatives --set php /usr/bin/php$PHP

COPY . /app
RUN composer global config --no-plugins allow-plugins.symfony/flex true
RUN composer global require --no-progress --no-scripts --no-plugins symfony/flex
RUN SYMFONY_REQUIRE=$SYMFONY_REQUIRE composer u --prefer-dist -n

CMD ["php", "vendor/bin/phpunit"]
